version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7.3
    working_directory: ~/npdoc_to_md
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          # install package (fetches setup.py in current directory)
          pip install .
          pip install codecov coverage pytest pytest-cov
          pytest -s -v npdoc_to_md --cov=npdoc_to_md
          codecov
workflows:
  version: 2
  workflow:
    jobs:
    - build
